/* config.h.  Generated by hand.  */

/* #undef DARWIN_DVD_IOCTL */
/* #undef DVD_STRUCT_IN_DVD_H */
/* #undef DVD_STRUCT_IN_LINUX_CDROM_H */
/* #undef DVD_STRUCT_IN_SYS_CDIO_H */
/* #undef DVD_STRUCT_IN_SYS_DVDIO_H */
/* #undef HAVE_BSD_DVD_STRUCT */
#define HAVE_DLFCN_H 1
/* #undef HAVE_DVD_H */
/* #undef HAVE_INTTYPES_H */
/* #undef HAVE_LINUX_CDROM_H */
/* #undef HAVE_LINUX_DVD_STRUCT */
#define HAVE_MEMORY_H 1
/* #undef HAVE_OPENBSD_DVD_STRUCT */
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
/* #undef HAVE_SYS_CDIO_H */
/* #undef HAVE_SYS_DVDIO_H */
#define HAVE_SYS_IOCTL_H 1
/* #undef HAVE_SYS_PARAM_H */
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
/* #undef HAVE_UNISTD_H */
#define HAVE_WINDOWS_H 1
#define HAVE_WINIOCTL_H 1
/* #undef HAVE__SYS_DEV_SCSI_SCSI_IOCTL_H */
#define PACKAGE "libdvdcss"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "libdvdcss"
#define PACKAGE_STRING "libdvdcss 1.3.0"
#define PACKAGE_TARNAME "libdvdcss"
#define PACKAGE_VERSION "1.3.0"
/* #undef SOLARIS_USCSI */
#define STDC_HEADERS 1
#define VERSION "1.3.0"
#define _WIN32_IE 0x0501
/* #undef const */
/* #undef inline */
/* #undef size_t */
#define HAVE_BROKEN_MKDIR 1
#define _CRT_SECURE_NO_WARNINGS 1
#define LIBDVDCSS_EXPORTS 1
